name: Update Version Of Helm Chart
on:
  workflow_dispatch:
    inputs:
      chartName:
        description: 'Name of Chart'
        required: true
      newVersion:
        description: 'New Version'
        required: false

jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Replace appVersion in Chart.yaml
      run: |
        echo '${{ github.event.inputs.newVersion }}'
        echo '${{ github.event.inputs.chartName }}'
        sed -i \
          's/^appVersion:.*$/appVersion: ${{ github.event.inputs.newVersion }}/' \
          './${{ github.event.inputs.chartName }}/Chart.yaml'
          
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: 'update version of ${{ github.event.inputs.chartName }} to ${{ github.event.inputs.newVersion }}'